### ISSUE TITLE
WeierstrassP derivative and half periods

### ISSUE THREAD

**Issue by brainjam** [paulmasson/math#1]
Now that the library has weierstrassP, it would be nice to have methods that return the derivative and half periods (like Mathematica's WeierstrassPPrime, WeierstrassHalfPeriodW1 , etc).

**Comment by paulmasson** [comment]
@brainjam thanks for the suggestion. `weierstrassPPrime()` is now available. Will add the half periods soon.

**Comment by paulmasson** [comment]
Functions now available include `inverseWeierstrassP()`, `weierstrassRoots()`, `weierstrassHalfPeriods()` and `weierstrassInvariants()`. Documentation is here:

https://paulmasson.github.io/math/docs/functions.html#elliptic

@brainjam thanks again for the suggestion! Let me know if you come across any issues using these functions.
