### ISSUE TITLE
besselYZero(0.0, 1.0) 

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#11]
`console.log(besselYZero(0.0, 1.0))` returns `2.3582698006047504`

but should return `0.893577`

**Comment by paulmasson** [comment]
Should be fixed in 8b7c12c. Thanks for catching this one also!

**Comment by axkr** [comment]
Is there a new release?

**Comment by paulmasson** [comment]
@axkr Yup! https://github.com/paulmasson/math/releases/tag/1.2.6
