### ISSUE TITLE
ellipticF(-1.5708,1.5708) hangs up in the browser

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#13]
`ellipticF(-1.5708,1.5708)` hangs up in the browser

**Comment by paulmasson** [comment]
Fixed, but came across problems with `ellipticPi` in the process. Will have a new release soon.

**Comment by paulmasson** [comment]
Version 1.2.7 now available.

Problem with ellipticPi was a difference between Mathematica and mpmath:
https://github.com/fredrik-johansson/mpmath/issues/517
