### ISSUE TITLE
Define betaRegularized

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#20]
Can you add a `betaRegularized` function?
The `beta()`and `gamma()` functions already exists in `math` project.

```
function betaRegularized(z, a, b) {
  return (beta(z, a, b)*gamma(a + b))/(gamma(a)*gamma(b));
}

function betaRegularized(z0, z1, a, b) {
  return ((-beta(z0, a, b) + beta(z1, a, b))*gamma(a + b))/(gamma(a)*gamma(b));
}
```

**Comment by paulmasson** [comment]
@axkr the order of arguments is different in Mathematica between `GammaRegularized` and `BetaRegularized`. Since I don't use these functions myself, is this expected behavior as far as you know?

**Comment by axkr** [comment]
Because I'm using the same name and arguments, I think this is expected behavior.
And it makes the mapping of functions to JavaScript much easier in the JS form converter:
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/form/output/JavaScriptFormFactory.java

**Comment by paulmasson** [comment]
@axkr added in 6880f95 along with update to `beta`. Will add `gammaRegularized` next.
