### ISSUE TITLE
Implement round, floor, ceil,... for complex arguments

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#21]
`Round[a,b]` in Mathematica is available for 2 arguments. 

Also `Round, Floor, Ceiling,... ` works on complex numbers by separately evaluating real and imaginary parts.
Can we have such functions also in math.js?

**Comment by paulmasson** [comment]
@axkr sorry it took so long to get to this! Added in 59659ae. Let me know if this takes care of the issue.

**Comment by axkr** [comment]
@paulmasson can you define `kronecker` as n-arg function?

If all n arguments are equal return 1 otherwise return 0.

**Comment by axkr** [comment]
Sign, IntegerPart and FractionalPart are other possible functions

**Comment by paulmasson** [comment]
All of these functions are now available in version [1.4.4](https://github.com/paulmasson/math/releases/tag/1.4.4). Thanks for the suggestions!
