### ISSUE TITLE
Where can I find the expIntegral function?

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#23]
I didn't see it in the online github interface?
* https://github.com/paulmasson/math/blob/6dcf33b5e28c70834f2cfc6506a024762fbbabf9/build/math.js#L2102

There are `expIntegralE` and `expIntegralEi` functions but no `expIntegral` ?

**Comment by paulmasson** [comment]
Simple oversight when renaming functions in #17. Fixed in 6c09d3e.

Thanks for catching this!
