### ISSUE TITLE
m seems to be unnecessary in carlsonRF

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#25]
`m` seems to be unnecessary in carlsonRF

https://github.com/paulmasson/math/blob/0eaa35ef23760fa7f7bf210aa87d6b32d0a157ad/src/functions/elliptic-integrals.js#L46

**Comment by paulmasson** [comment]
Right you are! Thanks for catching this. It also gave me the opportunity to review Carlson's 1995 paper and streamline the algorithm for carlsonRJ. Both fixed in e6729c4.
