### ISSUE TITLE
haversine and inverseHaversine

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#27]
Please implement haversine:
- https://en.wikipedia.org/wiki/Haversine_formula
as `1/2 * (1-Cos(x))`

and inverseHaversine
- https://en.wikipedia.org/wiki/Versine#ahav
as `2*ArcSin( Sqrt(x) )`

or alternative formula if numerically better suited.

**Comment by paulmasson** [comment]
@axkr done in 14c364a. Thanks for the suggestion!
