### ISSUE TITLE
hypergeometric2F1 function: X-values close to -1 cause an eternal while-loop

### ISSUE THREAD

**Issue by tornord** [paulmasson/math#29]
Hi!
x-values close to -1, eg -0.9999999999999976 results in an eternal while-loop, See https://github.com/paulmasson/math/blob/master/src/functions/hypergeometric.js#L384

E.g:
const y = hypergeometric2F1(1, 0.5, 1.5, -1.0000000000000024);
which calls hypergeometric2F1(1, 0.5, 1.5, -0.9999999999999976);

Can be solved by a tolerance check on line 372?: `if ( Math.abs(x+1)< tolerance )`. Or a max number of iterations check?
https://github.com/paulmasson/math/blob/master/src/functions/hypergeometric.js#L372

**Comment by paulmasson** [comment]
@tornord default tolerance for the library is 1e-10. This can be addressed by giving all functions the option of arbitrary precision. Same underlying issue as https://github.com/paulmasson/math/issues/28.

**Comment by tornord** [comment]
I like the lib! Impressive work!
In this case (and it's impossible to know as a user) hypergeometric2F1 hangs regardless of the tolerance value. 
hypergeometric2F1(1, 0.5, 1.5, -0.9999999999999976) causes it to hang, but hypergeometric2F1(1, 0.5, 1.5, -1) works.

**Comment by paulmasson** [comment]
@tornord recently tested `hypergeometric2F1(1, 0.5, 1.5, -0.9999999999999976)` and it doesn't hang but just takes a long time to evaluate. I've added a fix in 8ecb6f1 to address this. Thanks for the input!

**Comment by tornord** [comment]
Thanks @paulmasson !
