### ISSUE TITLE
arctan(x,y) should call Math.atan2(x,y) for real values

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#3]
arctan(x,y) should call Math.atan2(x,y) for real values

**Comment by paulmasson** [comment]
Since this library is focused on functions of complex variables, I'm not inclined to implement this. I know that Mathematica has this behavior but I've always found it a bit odd as it combines values from three different sheets of the complex function.

**Comment by axkr** [comment]
Ok.

I'd thought of the case, that atan2(y,x) is more stable when computing tangents using an expression like atan(y / x) and x is 0 or close to 0.

- https://en.wikipedia.org/wiki/Atan2#History_and_motivation

**Comment by paulmasson** [comment]
`Math.atan(1/0)` returns `Math.PI/2` so there shouldn't be any stability issues.
