### ISSUE TITLE
Implement numerical Binomial/Multinomial functions

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#30]
Does it make sense to implement a multinomial function derived from the `gamma` function:

$$Multinomial(x_1, x_2, x_3,...)  := \frac{\Gamma(\sum_i x_i + 1)}{\prod_i \Gamma(x_i+1)} $$

Or is there a faster approach using existing functions?

**Comment by paulmasson** [comment]
@axkr added this function in https://github.com/paulmasson/math/commit/c83fe19701038e0838666052742679cfdefdeff0 but decided it was cleaner to go through `factorial`. Had to make sure to catch cases of negative integers for cancellations at gamma function poles.

Let me know if you find any errors. Thanks for the suggestion!
