### ISSUE TITLE
NUM09-J. Do not use floating-point variables as loop counters

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#31]
My Java tool warns me about [NUM09-J. Do not use floating-point variables as loop counters](https://wiki.sei.cmu.edu/confluence/display/java/NUM09-J.+Do+not+use+floating-point+variables+as+loop+counters)
* https://wiki.sei.cmu.edu/confluence/display/java/NUM09-J.+Do+not+use+floating-point+variables+as+loop+counters

One corresponding example in `math.js` is:
* https://github.com/paulmasson/math/blob/0eaa35ef23760fa7f7bf210aa87d6b32d0a157ad/src/functions/elliptic-functions.js#L86

Should the floating-point iterations integer loop counter `i` not exceed a "configurated iteration limit" to be sure to stop the loop, for example if tolerance is choosen "too small"?

**Comment by paulmasson** [comment]
@axkr that rule is overly strict. The example you point out is the Jacobi theta functions, which converge very quickly. Iteration limits have their use for functions that can have convergence issues, for example `hypergeometric2F0`, but really aren't needed in practice most of the time.

**Comment by paulmasson** [comment]
If you find any counter examples to what I just said, then please let me know!
