### ISSUE TITLE
Documentation lists setPrecision instead of setPrecisionScale

### ISSUE THREAD

**Issue by mootari** [paulmasson/math#32]
The documentation lists the function [setPrecision](https://paulmasson.github.io/math/docs/arbitrary.html#:~:text=setPrecision), but the actual implementation is called [setPrecisionScale](https://github.com/paulmasson/math/blob/d994dda9dd8f399e0684f053b18b580fbc76fed1/src/operators.js#L18).

(Discovered while comparing documentation and source in https://observablehq.com/@ambassadors/library-analysis.)

**Comment by paulmasson** [comment]
@mootari right you are! Fixed in https://github.com/paulmasson/math/commit/9a969a2f8a1b6e591878e561f712f0178d96b846. Thanks!
