### ISSUE TITLE
Please implement the subfactorial function

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#34]
Please implement the `subfactorial(n)` function as 
```
gamma(n+1,-1)/E
```

- https://en.wikipedia.org/wiki/Derangement

Defintion for integers >= 0:
```
      ,
     |  1                             for n = 0
!n = {  0                             for n = 1
     |  (n - 1)*(!(n - 1) + !(n - 2)) for n > 1
      `
```

**Comment by paulmasson** [comment]
@axkr done in bc32df5. While this is not a function I plan on using anytime soon, it was a useful exercise. Had to fix a few things in the background along the way. Thanks for the suggestion!

**Comment by paulmasson** [comment]
@axkr after adding this function I noticed several issues that traced back to my implementation of the arbitrary precision natural logarithm. I think things are now fixed and streamlined in the process. Let me know if you notice any hangups or inaccuracies. Thanks again!

**Comment by axkr** [comment]
@paulmasson thank you for implementing. Do you create a new release?

**Comment by paulmasson** [comment]
@axkr done! Version [1.4.10](https://github.com/paulmasson/math/releases/tag/1.4.10).
