### ISSUE TITLE
sphericalBesselY(2.0,-5) negative result expected?

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#5]
```
console.log(sphericalBesselY(2.0,-5));
```

should return `-0.164995...` instead of  `0.16499545760108847` (Firefox console)?

**Comment by paulmasson** [comment]
Nice catch! This had to do with the phase of the square root in the definition of the function. It affected `sphericalBesselJ` as well. Both fixed in [Version 1.2.3](https://github.com/paulmasson/math/releases/tag/1.2.3). Thanks!

**Comment by paulmasson** [comment]
As a followup the same [issue](https://trac.sagemath.org/ticket/28474) occurs in SageMath. Trying to fix it there as well...
