### ISSUE TITLE
ellipticPi(2.0, 0.5) returns complex number?

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#6]
```
console.log(ellipticPi(2.0, 0.5));
```

should return `-0.313545...` instead of  `re: -0.31354468346461095; im: -1.8137993642342178` (Firefox console)?

​

**Comment by paulmasson** [comment]
@axkr `ellipticPi` normally has three arguments. When only two are supplied it assumes you want the complete integral `ellipticPi(2,pi/2,.5)`. This is consistent with Mathematica, where `EllipticPi[2, .5]` returns `-0.313545 - 1.8138 I`. How are you evaluating it to get only the real part?

**Comment by axkr** [comment]
I tried: https://www.wolframalpha.com/input/?i=EllipticPi%5B2%2C+.5%5D

**Comment by paulmasson** [comment]
Mathematica 10 returns a complex number, so this is an error in the website. You can verify this by comparing `EllipticPi[2, .5+1e-10I]` with `EllipticPi[2, .5-1e-10I]`. The imaginary part cannot just disappear across a branch cut.

**Comment by axkr** [comment]
In Version 12.0.0 of Wolfram cloud: 
![ellipticPi](https://user-images.githubusercontent.com/3109793/64993920-8a37ed00-d8d7-11e9-9ae4-44c65040a82b.png)
`EllipticPi[2, .5]` returns `-0.313545`

Has this changed in the latest Wolfram versions?

**Comment by paulmasson** [comment]
Apparently it has changed. Mathematica 10 on my desktop agrees with my library as well as [mpmath](http://mpmath.org), which is the numerical engine behind SageMath and can be tested live [here](https://sagecell.sagemath.org/?z=eJxLzcnJLCjJTI4vyNRQMNJRKMjUB5J6pgqaenkamgCYzgh0&lang=sage&interacts=eJyLjgUAARUAuQ==). Mathematica 12 on a Raspberry Pi returns the purely real result.
